export const productCategories = [  
    "Accessories",
    "Alcohol",
    "Art",
    "Books",
    "Drink",
    "Electronics",
    "Flower & Plants",
    "Food",
    "Gadgets",
    "Garden",
    "Grocery",
    "Home",
    "Jewelry",
    "Kids & Baby",
    "Men's Fashion",
    "Mobile",
    "Motorcycles",
    "Movies",
    "Music",
    "Office",
    "Pets",
    "Romantic",
    "Sport",
    "Toys"    
]

